### ISSUE TITLE
Upgrade to Grails 3.3.x

### ISSUE THREAD

**Issue by codeconsole** [gpc/grails-commentable#5]
I've created a pull request.

https://github.com/gpc/grails-commentable/pull/4

I've tested it with an 3.3.0 app and everything is working.
I also converted it to use a trait.

I also rolled back a horrible commit by Krazy Horse that broke everything.  Not sure how that got into the code base. If you follow the code logic, it doesn't work.

**Comment by codeconsole** [comment]
@graemerocher the plugin as is has been broken since 2015.  Any reason why not to maintain it? 
I was thinking about expanding on it a bit and would like your opinion.

**Comment by graemerocher** [comment]
Time. but you are welcome to take over maintenance and contribute. The plugin is part of the `gpc` org and extra contributors are welcome

**Comment by codeconsole** [comment]
@graemerocher I am more than happy to take over maintenance and contribute.  How do I get my pull request merged? Would you like to add me to the repository?

**Comment by graemerocher** [comment]
I have added you as a collaborator you should be able to merge and release the plugin yourself now. Thanks for the contribution

**Comment by codeconsole** [comment]
Strange, it is not giving me the option to merge a pull request.  It says "Only those with write access to this repository can merge pull requests."

**Comment by codeconsole** [comment]
@graemerocher I just confirmed I do not have write access.

$ git push
remote: Permission to gpc/grails-commentable.git denied to codeconsole.
fatal: unable to access 'https://github.com/gpc/grails-commentable/': The requested URL returned error: 403

**Comment by graemerocher** [comment]
You have not accepted the invite to the `gpc` org. It shows as pending. Please check your email.

**Comment by codeconsole** [comment]
Sorry, I had an old email associated with my github account.  Can you resend the invitation?

**Comment by codeconsole** [comment]
Never mind, I found the invitation on the repository page. Thanks
